module.exports = {
    SET: require('./SET'),
    INSERT: require('./INSERT'),
    SELECT: require('./SELECT'),
    FROM: require('./FROM'),
    INNER_JOIN: require('./INNER_JOIN'),
    LEFT_JOIN: require('./LEFT_JOIN'),
    RIGHT_JOIN: require('./RIGHT_JOIN'),
    ON: require('./ON'),
    WHERE: require('./WHERE'),
    AND: require('./AND'),
    OR: require('./OR'),
    ORDER_BY: require('./ORDER_BY'),
    ASC: require('./ASC'),
    DESC: require('./DESC'),
    UPDATE: require('./UPDATE'),
    DELETE: require('./DELETE'),
    LIMIT: require('./LIMIT'),
    EXECUT: require('./EXECUT')
};